# Generated by Selenium IDE
import unittest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test081001(unittest.TestCase):
    # 继承unittest.TestCase的类
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_081001(self):
        self.driver.get("https://www.baidu.com/")
        self.driver.set_window_size(683, 532)
        self.driver.find_element(By.ID, "kw").send_keys("重启之极海听雷")
        self.driver.find_element(By.ID, "su").click()
        time.sleep(6)


if __name__ == "__main__":
    # 执行类的入口
    unittest.main()